spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/granjapatos?createDatabaseIfNotExist=true
    username: root
    password: ADMIN

  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: never



